### ISSUE TITLE
Atk speed and movement speed

### ISSUE THREAD

**Issue by xinping1989** [AlSch092/NCShark#2]
I've seen people using the said atk speed and movement speed hack on Night crows can those things be done while tinkering with packets or need memory access/writing to do so?

**Comment by AlSch092** [comment]
Yes, it is possible in this game. Anything that can be done with memory edits can be done with packets and vice-versa. You can achieve the same effect by sending the packet multiple times when attacking.

**Comment by xinping1989** [comment]
> Yes, it is possible in this game. Anything that can be done with memory edits can be done with packets and vice-versa. You can achieve the same effect by sending the packet multiple times when attacking.

thank you
